config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :hotels

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  
  validates_presence_of :name, :description, :rooms
  
  has_many :reservations
  
  def available_rooms
    rooms - reservations.count 
  end
  
  def available_rooms_by_date(date)
    if !reservations.blank?
    reservations = reservations.where(:booked_date => date)
    rooms - reservations.count 
    else
    rooms  
    end    
  end
  
  
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  
  belongs_to :hotel
  belongs_to :user
  
  validates_presence_of :hotel, :user, :booked_date, :start_time, :end_time
  validates :rooms, presence: true, numericality: { greater_than: 0 }
  #validate :start_date_cannot_be_in_the_past
  validate :end_time_cannot_be_same_as_start_time
  validate :check_avilability_on_hotel_rooms_on_given_date
  validate :gap_between_end_time_and_start_time_should_be_30_min
  
  
  
  def end_time_cannot_be_same_as_start_time
    if start_time.to_i == end_time.to_i
      errors.add(:end_time, 'must not be same as start time')
    end
  end
  
  def gap_between_end_time_and_start_time_should_be_30_min
    if !start_time.blank? && !end_time.blank?      
      seconds_diff = (start_time - end_time).to_i.abs
      minutes = seconds_diff / 60
     if minutes < 30 
        errors.add(:end_time, 'must have 30 minutes time gap')
      end
    end
  end
  
 
  def check_avilability_on_hotel_rooms_on_given_date
    if !hotel.blank? && !self.booked_date.blank?
       if hotel.available_rooms_by_date(self.booked_date) == 0
         errors.add(:end_time, 'no rooms are available')  
      end
    end
  end
  
  
  def start_date_cannot_be_in_the_past
    if start_time && start_time < Date.today
      errors.add(:start_time, 'must be at least 15 minutes from present time')
    end
  end
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @hotels = Hotel.all.limit(3)
  end
  
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  
  def show
    @hotel = Hotel.find(params[:id])  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Online Booking </h1>
  <p>...</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>


<div class="row">
		<% @hotels.each_with_index do |hotel,i|%>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag "hotel#{i}.jpg"%>
      <div class="caption">
        <h3><%= hotel.name %></h3>
        <p><%= hotel.description %></p>
        <p>
        	<%= link_to "Book Now", hotel_path(hotel), :class => "btn btn-primary" %>
        	<%= link_to "View Details", hotel_path(hotel), :class => "btn btn-default" %>
        	</p>
      </div>
    </div>
  </div>
    <% end %>
</div>

app/views/hotels/show.html.erb
<div class="page-header">
  <h1><%= @hotel.name %> <small></small></h1>
</div>

<div class="row">
<div class="jumbotron">
<p>
<%= @hotel.description %>
</p>

<p>
Total Rooms: <%= @hotel.rooms %>	
</p>

<p>
Available Rooms: <%= @hotel.available_rooms %>	
</p>

<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Book Now</button>

</div>	
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Book your room</h4>
      </div>
      <div class="modal-body">
        <p>Select the dates you want to book </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Booking" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Online Booking Management</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path  %></li>
            <li><%= link_to "Hotels", "#"  %></li>
            <li><%= link_to "Resturants", "#"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-11">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>